import Foundation

struct Words {
    static let main = "main"
    static let weather = "weather"
    static let location = "location"
    static let temperature = "temperature"
    static let maxTemperature = "temp_max"
    static let minTemperature = "temp_min"
    static let feltTemperature = "feltTemperature"
    static let icon = "icon"
    static let backgroundImage = "backgroundImage"
    static let name = "name"
    static let temp = "temp"
    static let city = "city"
    static let list = "list"
    static let description = "description"
    static let descriptionToday = "descriptionToday"
    static let wind = "wind"
    static let windSpeed = "windSpeed"
    static let windDirection = "windDirection"
    static let speed = "speed"
    static let degree = "deg"
    static let day = "dt_txt"
    static let firstDayName = "firstDayName"
    static let secondDayName = "secondDayName"
    static let thirdDayName = "thirdDayName"
    static let fourthDayName = "fourthDayName"
    static let fifthDayName = "fifthDayName"
    static let firstDayIcon = "firstDayIcon"
    static let secondDayIcon = "secondDayIcon"
    static let thirdDayIcon = "thirdDayIcon"
    static let fourthDayIcon = "fourthDayIcon"
    static let fifthDayIcon = "fifthDayIcon"
    static let firstDayTemperature = "firstDayTemperature"
    static let secondDayTemperature = "secondDayTemperature"
    static let thirdDayTemperature = "thirdDayTemperature"
    static let fourthDayTemperature = "fourthDayTemperature"
    static let fifthDayTemperature = "fifthDayTemperature"
}
